Repository SOPT-all/35-COLLABORATION-iOS-LINKAREER, pull requests merged in 2024-11, with the labels that each got.

#2 [SETTING] 프로젝트 초기 세팅 (#1)
  LINKAREER-iOS/LINKAREER-iOS.xcodeproj/project.pbxproj
  LINKAREER-iOS/LINKAREER-iOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  LINKAREER-iOS/LINKAREER-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  LINKAREER-iOS/LINKAREER-iOS/Application/AppDelegate.swift
  LINKAREER-iOS/LINKAREER-iOS/Application/Base.lproj/LaunchScreen.storyboard
  LINKAREER-iOS/LINKAREER-iOS/Application/SceneDelegate.swift
  LINKAREER-iOS/LINKAREER-iOS/Global/Extension/NSObject+.swift
  LINKAREER-iOS/LINKAREER-iOS/Global/Extension/UILabel+.swift
  LINKAREER-iOS/LINKAREER-iOS/Global/Extension/UIStackView+.swift
  LINKAREER-iOS/LINKAREER-iOS/Global/Extension/UIView+.swift
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Assets.xcassets/Contents.json
  LINKAREER-iOS/LINKAREER-iOS/Global/Settings/Info.plist
  LINKAREER-iOS/LINKAREER-iOS/Presentation/Home/ViewController/ViewController.swift
Labels: 🌟 민서 🌟, ⚙️ setting ⚙️

#6 [Feat] Custom TabBar 구현 (#4)
  LINKAREER-iOS/LINKAREER-iOS/Application/SceneDelegate.swift
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Assets.xcassets/ic_calendar_active.imageset/Contents.json
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Assets.xcassets/ic_calendar_active.imageset/Property 1=ic_calendar_active.svg
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Assets.xcassets/ic_calendar_inactive.imageset/Contents.json
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Assets.xcassets/ic_calendar_inactive.imageset/Property 1=ic_calendar_inactive.svg
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Assets.xcassets/ic_chatting_active.imageset/Contents.json
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Assets.xcassets/ic_chatting_active.imageset/Property 1=ic_chatting_active.svg
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Assets.xcassets/ic_chatting_inactive.imageset/Contents.json
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Assets.xcassets/ic_chatting_inactive.imageset/Property 1=ic_chatting_inactive.svg
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Assets.xcassets/ic_community_active.imageset/Contents.json
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Assets.xcassets/ic_community_active.imageset/Property 1=ic_community_active.svg
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Assets.xcassets/ic_community_inactive.imageset/Contents.json
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Assets.xcassets/ic_community_inactive.imageset/Property 1=ic_community_inactive.svg
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Assets.xcassets/ic_home_active.imageset/Contents.json
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Assets.xcassets/ic_home_active.imageset/Property 1=ic_home_active.svg
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Assets.xcassets/ic_home_inactive.imageset/Contents.json
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Assets.xcassets/ic_home_inactive.imageset/Property 1=ic_home_inactive.svg
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Assets.xcassets/ic_menu_active.imageset/Contents.json
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Assets.xcassets/ic_menu_active.imageset/Property 1=ic_menu_active.svg
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Assets.xcassets/ic_menu_inactive.imageset/Contents.json
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Assets.xcassets/ic_menu_inactive.imageset/Property 1=ic_menu_inactive.svg
  LINKAREER-iOS/LINKAREER-iOS/Presentation/TabBar/TabBarController.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/TabBar/TabBarItem.swift
Labels: 🎀 가현 🎀, 💡 feature 💡

#13 [FIX] 폰트 파일 문제 해결 (#12)
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Font/FontStyle.swift
  LINKAREER-iOS/LINKAREER-iOS/Global/Settings/Info.plist
Labels: 👔 재현 👔, 🛠️ fix 🛠️

#15 [FEAT] 채팅 인증 초기 화면 (#8)
  LINKAREER-iOS/LINKAREER-iOS/Presentation/ChatCertification/Initial/Model/CertificationInitialModel.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/ChatCertification/Initial/View/ChatCertificationInitialCell.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/ChatCertification/Initial/View/ChatCertificationInitialView.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/ChatCertification/Initial/ViewController/ChatCertificationInitialViewController.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/TabBar/TabBarItem.swift
Labels: 🎀 가현 🎀, 💡 feature 💡

#14 [FEAT] 가로 스크롤 뷰 구현 (#9)
  LINKAREER-iOS/LINKAREER-iOS/Presentation/NewBieIntern/Controller/NewbieInternViewController.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/NewBieIntern/Function/PaddedUILabel.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/NewBieIntern/Model/CompanyDayCardDataModel.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/NewBieIntern/View/Section2/CompanyDayCardCell.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/NewBieIntern/View/Section2/CompanyHorizontalScrollview.swift
Labels: 👔 재현 👔, 💡 feature 💡

#18 [FEAT] HomeView UI 구현 (#11)
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Assets.xcassets/Icons/ic_scrap_b_default.imageset/Contents.json
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Assets.xcassets/Icons/ic_scrap_b_default.imageset/Property 1=ic_scrap_b_default.svg
  LINKAREER-iOS/LINKAREER-iOS/Global/UIComponents/BoardCell.swift
  LINKAREER-iOS/LINKAREER-iOS/Global/UIComponents/CategorySelectorCell.swift
  LINKAREER-iOS/LINKAREER-iOS/Global/UIComponents/PolicyFooterView.swift
  LINKAREER-iOS/LINKAREER-iOS/Global/UIComponents/TagHeaderView.swift
  LINKAREER-iOS/LINKAREER-iOS/Global/Utils/Enums/HomeSection.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/Home/Model/HomeModel.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/Home/View/BottomPageControlView.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/Home/View/Cell/HomeBannerCell.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/Home/View/HomeView.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/Home/ViewController/HomeViewController.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/Home/ViewController/ViewController.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/TabBar/TabBarItem.swift
Labels: 🌟 민서 🌟, 💡 feature 💡

#20 [FEAT] 채팅 인증 과정, 완료 화면 (#16)
  LINKAREER-iOS/LINKAREER-iOS/Presentation/ChatCertification/Complete/View/ChatCertificationCompleteView.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/ChatCertification/Complete/ViewController/ChatCertificationCompleteViewController.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/ChatCertification/Initial/View/ChatCertificationInitialView.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/ChatCertification/Initial/ViewController/ChatCertificationInitialViewController.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/ChatCertification/Procedure/View/CaptureButton.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/ChatCertification/Procedure/View/ChatCertificationProcedureView.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/ChatCertification/Procedure/ViewController/ChatCertificationProcedureViewController.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/TabBar/TabBarItem.swift
Labels: 🎀 가현 🎀, 💡 feature 💡

#24 [Feat] 채팅 리스트 및 카테고리 (#21)
  LINKAREER-iOS/LINKAREER-iOS/Presentation/Chat/Model/ChatModel.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/Chat/View/CategoryCollectionViewCell.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/Chat/View/ChatListCollectionViewCell.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/Chat/View/ChatView.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/Chat/View/EmptyView.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/Chat/ViewController/ChatViewController.swift
Labels: 🎀 가현 🎀, 💡 feature 💡

#27 [Feat] Custom NavigationBar, SearchView (#25)
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Assets.xcassets/Icons/ic_calendar_w_36.imageset/Contents.json
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Assets.xcassets/Icons/ic_calendar_w_36.imageset/ic_calendar_w_36.svg
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Assets.xcassets/img_logo.imageset/Contents.json
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Assets.xcassets/img_logo.imageset/Group 1686557727.svg
  LINKAREER-iOS/LINKAREER-iOS/Global/UIComponents/CustomNavigationController.swift
  LINKAREER-iOS/LINKAREER-iOS/Global/UIComponents/CustomSearchView.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/Chat/View/ChatView.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/TabBar/TabBarItem.swift
Labels: 🎀 가현 🎀, 💡 feature 💡

#35 [FEAT] HomeView 상단 섹션 구현 및 레이아웃 수정 (#28)
  LINKAREER-iOS/LINKAREER-iOS.xcodeproj/project.pbxproj
  LINKAREER-iOS/LINKAREER-iOS/Global/Extension/UIButton+.swift
  LINKAREER-iOS/LINKAREER-iOS/Global/UIComponents/SegmentStackView.swift
  LINKAREER-iOS/LINKAREER-iOS/Global/UIComponents/TagHeaderView.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/Home/View/Cell/HomeBannerCell.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/Home/View/HomeView.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/Home/View/SectionBackgroundView.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/Home/ViewController/HomeViewController.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/NewBieIntern/View/Section2/CompanyDayCardCell.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/TabBar/TabBarController.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/TabBar/TabBarItem.swift
Labels: 🌟 민서 🌟, 💡 feature 💡

#34 [Feat] 뉴비인턴뷰 완성인데 이제 그 질문을 곁들인 (#30)
  LINKAREER-iOS/LINKAREER-iOS/Presentation/NewBieIntern/Controller/NewbieInternViewController.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/NewBieIntern/Model/CompanyDayCardModel.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/NewBieIntern/View/Header/NewbieHeaderView.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/NewBieIntern/View/Section1/CompanyHorizontalScrollHeaderCollectionViewCell.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/NewBieIntern/View/Section1/ScrollviewHeaderViewCell.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/NewBieIntern/View/Section2/CompanyDayCardCell.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/NewBieIntern/View/Section2/CompanyHorizontalScrollview.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/NewBieIntern/View/Section5/MentorPostViewCell.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/NewBieIntern/View/Section6/ChatReSearchButtonView.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/NewBieIntern/View/Section6/CompanyMentorCollectionViewCell.swift
Labels: 👔 재현 👔, 💡 feature 💡

#37 [FEAT] 같은 관심사 게시글 네트워크 통신 (#36)
  LINKAREER-iOS/LINKAREER-iOS/Global/Extension/UIImageView+.swift
  LINKAREER-iOS/LINKAREER-iOS/Global/UIComponents/BoardCell.swift
  LINKAREER-iOS/LINKAREER-iOS/Network/Base/NetworkService.swift
  LINKAREER-iOS/LINKAREER-iOS/Network/Home/DTO/GetPostListResponse.swift
  LINKAREER-iOS/LINKAREER-iOS/Network/Home/HomeService.swift
  LINKAREER-iOS/LINKAREER-iOS/Network/Home/HomeTargetType.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/Home/Model/HomeModel.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/Home/ViewController/HomeViewController.swift
Labels: 🌟 민서 🌟, 💡 feature 💡

#40 [FEAT] 뉴비뷰 붙이기 & 네트워크 붙이기 (#38)
  LINKAREER-iOS/LINKAREER-iOS/Network/Base/NetworkService.swift
  LINKAREER-iOS/LINKAREER-iOS/Network/NewbieNetwork/DTO.swift
  LINKAREER-iOS/LINKAREER-iOS/Network/NewbieNetwork/NewbieService.swift
  LINKAREER-iOS/LINKAREER-iOS/Network/NewbieNetwork/NewbieTargetType.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/Home/ViewController/HomeViewController.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/NewBieIntern/Controller/NewbieInternViewController.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/NewBieIntern/Model/CompanyBigCardDataModel.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/NewBieIntern/Model/CompanyDayCardModel.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/NewBieIntern/Model/JobSuccessCardModel.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/NewBieIntern/Model/NoTagHeaderModel.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/NewBieIntern/View/Section2/CompanyDayCardCell.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/NewBieIntern/View/Section5/MentorPostViewCell.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/NewBieIntern/View/Section6/CompanyMentorCollectionViewCell.swift
Labels: 👔 재현 👔, 💡 feature 💡

#42 [Network] Post, Delete API 연결 (#41)
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Assets.xcassets/Icons/ic_scrap_b_active.imageset/Contents.json
  LINKAREER-iOS/LINKAREER-iOS/Global/Resources/Assets.xcassets/Icons/ic_scrap_b_active.imageset/Property 1=ic_scrap_b_active.svg
  LINKAREER-iOS/LINKAREER-iOS/Network/NewbieNetwork/BookMarkResponseDTO.swift
  LINKAREER-iOS/LINKAREER-iOS/Network/NewbieNetwork/NewbieService.swift
  LINKAREER-iOS/LINKAREER-iOS/Network/NewbieNetwork/NewbieTargetType.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/Home/ViewController/HomeViewController.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/NewBieIntern/Controller/NewbieInternViewController.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/NewBieIntern/View/Section2/CompanyDayCardCell.swift
  LINKAREER-iOS/LINKAREER-iOS/Presentation/NewBieIntern/View/Section2/CompanyHorizontalScrollview.swift
Labels: 🎀 가현 🎀
